services:
  - type: web
    name: food-delivery-backend
    runtime: docker
    dockerfilePath: ./FoodDeliveryBackend/Dockerfile
    dockerContext: ./FoodDeliveryBackend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false

databases:
  - name: food-delivery-db
    databaseName: food_delivery_db
    plan: free
